name = "DiffEqFinancial"
uuid = "5a0ffddc-d203-54b0-88ba-2c03c0fc2e67"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "v2.1.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqNoiseProcess = "77a26b50-5914-5dd7-bc55-306e6241c503"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"

[compat]
julia = "1"
DiffEqBase = "6"
DiffEqNoiseProcess = "3"
RandomNumbers = "1"

[extras]
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"

[targets]
test = ["Test", "StochasticDiffEq"]
